##Data Reading and Preparation

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data = "https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv"


In [3]:
!wget $data -O data-homework3.csv

--2023-10-08 19:57:43--  https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1475504 (1.4M) [text/plain]
Saving to: ‘data-homework3.csv’

data-homework3.csv  100%[===================>]   1.41M  --.-KB/s    in 0.07s   

2023-10-08 19:57:43 (21.6 MB/s) - ‘data-homework3.csv’ saved [1475504/1475504]



In [53]:
df = pd.read_csv('data-homework3.csv')

In [54]:
X = df[["Make", "Model", "Year","Engine HP", "Engine Cylinders","Transmission Type","Vehicle Style","highway MPG","city mpg"]]

In [55]:
y=df[["MSRP"]]

In [56]:
X.columns = X.columns.str.replace(' ', '_').str.lower()


In [57]:
X.isna().sum()

make                  0
model                 0
year                  0
engine_hp            69
engine_cylinders     30
transmission_type     0
vehicle_style         0
highway_mpg           0
city_mpg              0
dtype: int64

In [58]:
X.fillna(0, inplace=True)

<ipython-input-58-67b4599ed24c>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X.fillna(0, inplace=True)


In [59]:
y.rename(columns = {'MSRP':'price'}, inplace = True)


<ipython-input-59-f53a3ffce32c>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y.rename(columns = {'MSRP':'price'}, inplace = True)


##Q1

In [11]:
X.transmission_type.value_counts()

AUTOMATIC           8266
MANUAL              2935
AUTOMATED_MANUAL     626
DIRECT_DRIVE          68
UNKNOWN               19
Name: transmission_type, dtype: int64

##Q.2

In [61]:
X.dtypes

make                  object
model                 object
year                   int64
engine_hp            float64
engine_cylinders     float64
transmission_type     object
vehicle_style         object
highway_mpg            int64
city_mpg               int64
dtype: object

In [60]:
numerical =["year","engine_hp","engine_cylinders", "highway_mpg", "city_mpg"]

In [ ]:
matrix =X.corr()

<ipython-input-49-26b75b1faa0c>:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  matrix =X.corr()


In [ ]:
matrix

year  engine_hp  engine_cylinders  highway_mpg  city_mpg
year              1.000000   0.338714         -0.040708     0.258240  0.198171
engine_hp         0.338714   1.000000          0.774851    -0.415707 -0.424918
engine_cylinders -0.040708   0.774851          1.000000    -0.614541 -0.587306
highway_mpg       0.258240  -0.415707         -0.614541     1.000000  0.886829
city_mpg          0.198171  -0.424918         -0.587306     0.886829  1.000000

##Q.3

In [62]:
y['above_average']=(y.price>y.price.mean()).astype(int)
y

<ipython-input-62-e9fe0fe52852>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y['above_average']=(y.price>y.price.mean()).astype(int)


price  above_average
0      46135              1
1      40650              1
2      36350              0
3      29450              0
4      34500              0
...      ...            ...
11909  46120              1
11910  56670              1
11911  50620              1
11912  50920              1
11913  28995              0

[11914 rows x 2 columns]

In [63]:
y=y.drop(['price'], axis=1)

In [64]:
from sklearn.model_selection import train_test_split

In [129]:
X_full_train,X_test, y_full_train, y_test = train_test_split(X, y,test_size=0.2, random_state=1)

In [108]:
X_full_train.shape

(9531, 9)

In [67]:
y_full_train.shape

(9531, 1)

In [130]:
X_train,X_val, y_train, y_val =  train_test_split(X_full_train,y_full_train, test_size=0.25,random_state=1)

In [131]:
X_train

make              model  year  engine_hp  engine_cylinders  \
5727      Toyota  Highlander Hybrid  2016      280.0               6.0   
5814   Chevrolet     Impala Limited  2014      300.0               6.0   
8450       Buick              Regal  2016      259.0               4.0   
2396  Volkswagen                 CC  2015      280.0               6.0   
5494       Dodge      Grand Caravan  2016      283.0               6.0   
...          ...                ...   ...        ...               ...   
5864      Subaru            Impreza  2015      148.0               4.0   
7924    Infiniti               QX50  2016      325.0               6.0   
4719       Honda                Fit  2017      130.0               4.0   
63          Audi                200  1991      162.0               5.0   
7918    Infiniti                QX4  2003      240.0               6.0   

     transmission_type      vehicle_style  highway_mpg  city_mpg  
5727         AUTOMATIC            4dr SUV           28        27  
5814         AUTOMATIC              Sedan           30        18  
8450         AUTOMATIC              Sedan           27        19  
2396  AUTOMATED_MANUAL              Sedan           25        17  
5494         AUTOMATIC  Passenger Minivan           25        17  
...                ...                ...          ...       ...  
5864            MANUAL      4dr Hatchback           33        24  
7924         AUTOMATIC            4dr SUV           24        17  
4719         AUTOMATIC      4dr Hatchback           37        32  
63           AUTOMATIC              Sedan           20        16  
7918         AUTOMATIC            4dr SUV           18        14  

[7148 rows x 9 columns]

In [20]:
from sklearn.metrics import mutual_info_score

In [69]:
categorical=["make","model","transmission_type","vehicle_style"]

In [ ]:
def mutual_info_churn_score(series):
  return mutual_info_score(y_train.above_average, series)

In [ ]:
mi = X_train[categorical].apply(mutual_info_churn_score)
mi = round(mi,2)
mi.sort_values(ascending=False)

model                0.47
make                 0.24
vehicle_style        0.08
transmission_type    0.02
dtype: float64

##Q.4

In [70]:
from sklearn.feature_extraction import DictVectorizer

In [71]:
dv = DictVectorizer(sparse=False)

In [72]:
train_dicts = X_train[categorical+numerical].to_dict(orient='records')
X_train = dv.fit_transform(train_dicts)

In [ ]:
dv.get_feature_names_out()

In [74]:
val_dicts = X_val[categorical+numerical].to_dict(orient='records')
X_val = dv.transform(val_dicts)

In [75]:
from sklearn.linear_model import LogisticRegression

In [76]:
model = LogisticRegression(solver='liblinear', C=10, max_iter=1000, random_state=42)


In [77]:
model.fit(X_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=10, max_iter=1000, random_state=42, solver='liblinear')

In [81]:
y_val

above_average
323                1
4691               0
8418               0
9078               0
10856              0
...              ...
2191               1
10615              0
6292               0
11523              1
4353               0

[2383 rows x 1 columns]

In [78]:
from sklearn.metrics import accuracy_score

In [79]:
y_pred= model.predict(X_val)
accuracy = np.round(accuracy_score(y_val, y_pred),2)


In [80]:
accuracy

0.94

In [95]:
y_predict= model.predict_proba(X_val)[:,1]
churn_decision = (y_predict >0.5)
(y_val.values.reshape(-1)==churn_decision).mean()


0.9353755770037767

In [90]:
churn_decision

array([ True, False, False, ..., False,  True, False])

In [94]:
y_val.values.reshape(-1)

array([1, 0, 0, ..., 0, 1, 0])

In [87]:
y_val

above_average
323                1
4691               0
8418               0
9078               0
10856              0
...              ...
2191               1
10615              0
6292               0
11523              1
4353               0

[2383 rows x 1 columns]

In [83]:
churn_decision

array([ True, False, False, ..., False,  True, False])

##Q.5

In [38]:
feature_names = categorical+numerical
num_of_features= len(feature_names)

In [47]:
feature_names

['make',
 'model',
 'transmission_type',
 'vehicle_style',
 'year',
 'engine_hp',
 'engine_cylinders',
 'highway_mpg']

In [40]:
X_train

array([[2.700e+01, 6.000e+00, 2.800e+02, ..., 0.000e+00, 0.000e+00,
        2.016e+03],
       [1.800e+01, 6.000e+00, 3.000e+02, ..., 1.000e+00, 0.000e+00,
        2.014e+03],
       [1.900e+01, 4.000e+00, 2.590e+02, ..., 1.000e+00, 0.000e+00,
        2.016e+03],
       ...,
       [3.200e+01, 4.000e+00, 1.300e+02, ..., 0.000e+00, 0.000e+00,
        2.017e+03],
       [1.600e+01, 5.000e+00, 1.620e+02, ..., 1.000e+00, 0.000e+00,
        1.991e+03],
       [1.400e+01, 6.000e+00, 2.400e+02, ..., 0.000e+00, 0.000e+00,
        2.003e+03]])

In [114]:
y_val.values.reshape(-1)

array([1, 0, 0, ..., 0, 1, 0])

In [115]:
y_pred

array([1, 0, 1, ..., 0, 1, 0])

In [142]:
for feature in feature_names:
  subset = feature_names.copy()
  subset.remove(feature)
  dv = DictVectorizer(sparse=False)
  train_dicts = X_train[subset].to_dict(orient='records')
  X_train_f = dv.fit_transform(train_dicts)
  val_dicts = X_val[subset].to_dict(orient='records')
  X_val_f = dv.transform(val_dicts)
  model = LogisticRegression(solver='liblinear', C=10, max_iter=1000, random_state=42)
  model.fit(X_train_f,y_train)
  y_pred= model.predict(X_val_f)
  accuracy = (accuracy_score(y_val, y_pred))
  diff =0.9353755770037767-accuracy
  print("acc is %f difference is is %.7f excluding the feature %s" %(accuracy,diff,feature) )


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


acc is 0.943349 difference is is -0.0079731 excluding the feature make


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


acc is 0.908519 difference is is 0.0268569 excluding the feature model


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


acc is 0.944608 difference is is -0.0092321 excluding the feature transmission_type


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


acc is 0.937893 difference is is -0.0025178 excluding the feature vehicle_style


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


acc is 0.950902 difference is is -0.0155266 excluding the feature year


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


acc is 0.907260 difference is is 0.0281158 excluding the feature engine_hp


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


acc is 0.945867 difference is is -0.0104910 excluding the feature engine_cylinders
acc is 0.916911 difference is is 0.0184641 excluding the feature highway_mpg


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [138]:
original_score = 0.9353755770037767

scores = pd.DataFrame(columns=['eliminated_feature', 'accuracy', 'difference'])
for feature in feature_names:
    subset = feature_names.copy()
    subset.remove(feature)

    dv = DictVectorizer(sparse=False)
    train_dict = X_train[subset].to_dict(orient='records')
    X_train_f = dv.fit_transform(train_dict)

    model = LogisticRegression(solver='liblinear', max_iter=1000, C=10, random_state=42)
    model.fit(X_train_f, y_train)

    val_dict = X_val[subset].to_dict(orient='records')
    X_val_f = dv.transform(val_dict)

    y_pred = model.predict(X_val_f)
    score = accuracy_score(y_val, y_pred)

    scores.loc[len(scores)] = [feature, score, original_score - score]

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for exam

In [139]:
scores

eliminated_feature  accuracy  difference
0               make  0.943349   -0.007973
1              model  0.908519    0.026857
2  transmission_type  0.944608   -0.009232
3      vehicle_style  0.937893   -0.002518
4               year  0.950902   -0.015527
5          engine_hp  0.907260    0.028116
6   engine_cylinders  0.945867   -0.010491
7        highway_mpg  0.916911    0.018464

In [140]:
min_diff = scores.difference.min()
scores[scores.difference == min_diff]

eliminated_feature  accuracy  difference
4               year  0.950902   -0.015527

##Q.6

In [ ]:
X = df[["Make", "Model", "Year","Engine HP", "Engine Cylinders","Transmission Type","Vehicle Style","highway MPG","city mpg"]]


In [ ]:
X.columns = X.columns.str.replace(' ', '_').str.lower()


In [ ]:
X.fillna(0, inplace=True)

<ipython-input-6-67b4599ed24c>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X.fillna(0, inplace=True)


In [ ]:
y = df[["MSRP"]]
y.rename(columns = {'MSRP':'price'}, inplace = True)
y = np.log1p(y.values)


<ipython-input-7-22f79618d82c>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y.rename(columns = {'MSRP':'price'}, inplace = True)


In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_full_train,X_test, y_full_train, y_test = train_test_split(X, y,test_size=0.2, random_state=1)

In [ ]:
X_train,X_val, y_train, y_val =  train_test_split(X_full_train,y_full_train, test_size=0.25,random_state=1)

In [ ]:
X_train

make              model  year  engine_hp  engine_cylinders  \
5727      Toyota  Highlander Hybrid  2016      280.0               6.0   
5814   Chevrolet     Impala Limited  2014      300.0               6.0   
8450       Buick              Regal  2016      259.0               4.0   
2396  Volkswagen                 CC  2015      280.0               6.0   
5494       Dodge      Grand Caravan  2016      283.0               6.0   
...          ...                ...   ...        ...               ...   
5864      Subaru            Impreza  2015      148.0               4.0   
7924    Infiniti               QX50  2016      325.0               6.0   
4719       Honda                Fit  2017      130.0               4.0   
63          Audi                200  1991      162.0               5.0   
7918    Infiniti                QX4  2003      240.0               6.0   

     transmission_type      vehicle_style  highway_mpg  city_mpg  
5727         AUTOMATIC            4dr SUV           28        27  
5814         AUTOMATIC              Sedan           30        18  
8450         AUTOMATIC              Sedan           27        19  
2396  AUTOMATED_MANUAL              Sedan           25        17  
5494         AUTOMATIC  Passenger Minivan           25        17  
...                ...                ...          ...       ...  
5864            MANUAL      4dr Hatchback           33        24  
7924         AUTOMATIC            4dr SUV           24        17  
4719         AUTOMATIC      4dr Hatchback           37        32  
63           AUTOMATIC              Sedan           20        16  
7918         AUTOMATIC            4dr SUV           18        14  

[7148 rows x 9 columns]

In [ ]:
from sklearn.feature_extraction import DictVectorizer

In [ ]:
dv = DictVectorizer(sparse=False)

In [ ]:
train_dicts = X_train[categorical+numerical].to_dict(orient='records')
X_train = dv.fit_transform(train_dicts)

In [ ]:
val_dicts = X_val[categorical+numerical].to_dict(orient='records')
X_val = dv.transform(val_dicts)

In [ ]:
def rmse(y, y_pred):
  error = y-y_pred
  squared_error = error**2
  mean_squared_error =squared_error.mean()
  root_mean_squared_error=np.sqrt(mean_squared_error)
  return root_mean_squared_error

In [ ]:
from sklearn.linear_model import Ridge


In [ ]:
X_train.shape

(7148, 954)

In [ ]:
len(set(dv.get_feature_names_out()))

954

In [ ]:
for a in [0, 0.01, 0.1, 1, 10]:
  model= Ridge(solver='sag', random_state=42, alpha=a)
  model.fit(X_train,y_train)
  y_pred= model.predict(X_val)
  rmse_val= rmse(y_val,y_pred)
  print("rmse = %f , alpha=%f"%(rmse_val,a))

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


rmse = 0.485990 , alpha=0.000000


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


rmse = 0.485991 , alpha=0.010000


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


rmse = 0.485992 , alpha=0.100000


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


rmse = 0.486010 , alpha=1.000000
rmse = 0.486191 , alpha=10.000000


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
